name: Deploy Azure Resources

on:
  push:
    branches:
      - main
  workflow_dispatch:
  #   inputs:
  #     environmentName:
  #       description: 'The name of the environment'
  #       required: true
  #       default: "pslTestAuto2"
  #     location:
  #       description: 'The location for the deployment'
  #       required: true
  #       default: "eastus2"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version  # Verify installation

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Install Bicep CLI
        run: az bicep install

      - name: Deploy Bicep Template
        run: |
          set -e
          echo "Environment Name: ${{ github.event.inputs.environmentName }}"
          echo "Location: ${{ github.event.inputs.location }}"

          az deployment sub create \
            --name autoDemo \
            --location eastus \
            --template-file infra/main.bicep \
            --parameters environmentName=pslautomation2 location=eastus2
