name: Build Docker Images

on:
  push:
    branches:
      - main
      - dev
      - demo
  pull_request:
    branches:
      - main
      - dev
      - demo
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  merge_group:

jobs:
  docker-build:
    strategy:
      matrix:
        include:
          - app_name: rag-adminwebapp
            dockerfile: docker/Admin.Dockerfile
          - app_name: rag-backend
            dockerfile: docker/Backend.Dockerfile
          - app_name: rag-webapp
            dockerfile: docker/Frontend.Dockerfile
    uses: ./.github/workflows/build-docker.yml
    with:
      old_registry: ${{ github.ref_name == 'main' && 'cwydcontainerregpk.azurecr.io' }}
      new_registry: 'cwyddockervalidation.azurecr.io'
      old_username: ${{ github.ref_name == 'main' && 'cwydcontainerregpk' }}
      new_username: 'cwyddockervalidation'
      app_name: ${{ matrix.app_name }}
      dockerfile: ${{ matrix.dockerfile }}
      push: ${{ github.ref_name == 'main' || github.ref_name == 'dev' || github.ref_name == 'demo' }}
    secrets: inherit
