name: Deploy Azure Resources-Updated

on:
  push:
    branches:
      - PSL-Automation-Flow-Draft

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version  # Verify installation

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AUTO_AZURE_CLIENT_ID }} -p ${{ secrets.AUTO_AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AUTO_AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AUTO_AZURE_SUBSCRIPTION_ID }}

      - name: Install Bicep CLI
        run: az bicep install

      - name: Deploy Bicep Template
        run: |
          set -e
          az deployment sub create \
            --name autoDemo \
            --location eastus \
            --template-file infra/main.bicep \
            --parameters environmentName=pslautomation location=eastus2

      - name: Send Success Email
        if: ${{ success() }}
        run: |
          echo "Deployment succeeded" | mail -s "Azure Deployment Success" v-pmalusare@microsoft.com

      - name: Send Failure Email
        if: ${{ failure() }}
        run: |
          echo "Deployment failed" | mail -s "Azure Deployment Failure" v-pmalusare@microsoft.com
