name: Deploy Azure Resources-Updated

on:
  push:
    branches:
      - PSL-Automation-Flow-Draft

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version  # Verify installation

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AUTO_AZURE_CLIENT_ID }} -p ${{ secrets.AUTO_AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AUTO_AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AUTO_AZURE_SUBSCRIPTION_ID }}

      - name: Install Bicep CLI
        run: az bicep install

      - name: Install mailutils
        run: sudo apt-get update && sudo apt-get install -y mailutils

      - name: Deploy Bicep Template
        id: deploy
        run: |
          set -e
          output=$(az deployment sub create \
            --name autoDemo \
            --location eastus \
            --template-file infra/main.bicep \
            --parameters environmentName=pslautomation location=eastus2 \
            --query-string "{outputs: properties.outputs, error: properties.error}" \
            -o json 2>&1)



      - name: Send Email
        run: |
          status=${{ steps.deploy.outputs.status }}
          output=${{ steps.deploy.outputs.output }}

          if [ "$status" == "succeeded" ]; then
            echo "Deployment succeeded. Details: $output" | mail -s "Azure Deployment Success" v-pmalusare@microsoft.com
          else
            echo "Deployment failed. Error details: $output" | mail -s "Azure Deployment Failure" v-pmalusare@microsoft.com
          fi
